export const Assets = {
  toast_success_icon: require('../assets/toast_success.png'),
  toast_error_icon: require('../assets/toast_error.png'),
  toast_info_icon: require('../assets/toast_info.png'),
  send_blue_icon: require('../assets/send_blue.png'),
  send_grey_icon: require('../assets/send_grey.png'),
  send_white_icon: require('../assets/send_white.png'),
  attachment_blue_icon: require('../assets/attachment_blue.png'),
  arrow_back_black_icon: require('../assets/arrow_back_black.png'),
  download: require('../assets/download.png'),
  close_black_icon: require('../assets/close_black.png'),
  camera_icon: require('../assets/camera.png'),
  gallery_icon: require('../assets/gallery.png'),
  video_icon: require('../assets/video.png'),
  document_icon: require('../assets/document.png'),
  logout_icon: require('../assets/logout.png'),

  defaultIcon: require('./extension/default.png'),
  docIcon: require('./extension/doc.png'),
  docxIcon: require('./extension/docx.png'),
  jpegIcon: require('./extension/jpeg.png'),
  jpgIcon: require('./extension/jpg.png'),
  mp4Icon: require('./extension/mp4.png'),
  odcIcon: require('./extension/odc.png'),
  odtIcon: require('./extension/odt.png'),
  pdfIcon: require('./extension/pdf.png'),
  pngIcon: require('./extension/png.png'),
  pptIcon: require('./extension/ppt.png'),
  pptxIcon: require('./extension/pptx.png'),
  rarIcon: require('./extension/rar.png'),
  svgIcon: require('./extension/svg.png'),
  xlsIcon: require('./extension/xls.png'),
  xlsxIcon: require('./extension/xlsx.png'),
  xmlIcon: require('./extension/xml.png'),
  zipIcon: require('./extension/zip.png'),
  csvIcon: require('./extension/csv.png'),

  no_chat: require('../assets/no_chat.png'),
  no_internet: require('../assets/no_internet.png'),
};
